<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UP95368" failures="1" tests="2" name="Web Tests" time="12.271" errors="0" timestamp="2022-07-05T21:29:26 IDT">
  <testcase classname="sanity.ToDoListElectron" name="test01_addAndVerifyNewTask" time="1.253"/>
  <testcase classname="sanity.ToDoListElectron" name="test02_addAndVerifyNewTasks" time="0.285">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at extensions.Verifications.verifyNumber(Verifications.java:56)
at sanity.ToDoListElectron.test02_addAndVerifyNewTasks(ToDoListElectron.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test02_addAndVerifyNewTasks -->
</testsuite> <!-- Web Tests -->
